services:
    ollama:
        build:
            context: .
            dockerfile: Dockerfile.ollama
        container_name: ollama
        ports:
            - "11434:11434" # Expose Ollama API
        environment:
            OLLAMA_ORIGINS: "chrome-extension://*,moz-extension://*,safari-web-extension://*,http://n8n:5678,http://localhost:5678"
            OLLAMA_HOST: "0.0.0.0" # Important! Bind to all interfaces so n8n can connect
        volumes:
            - ollama_data:/root/.ollama # Persist models between container restarts
        networks:
            - app-network
        restart: unless-stopped
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]

    postgres:
        image: postgres:16-alpine
        container_name: postgres
        networks:
            - app-network
        restart: unless-stopped
        environment:
            POSTGRES_USER: n8n
            POSTGRES_PASSWORD: n8n
            POSTGRES_DB: n8n
        volumes:
            - postgres_storage:/var/lib/postgresql/data

    n8n:
        image: n8nio/n8n:latest
        container_name: n8n
        networks:
            - app-network
        restart: unless-stopped
        ports:
            - "5678:5678"
        environment:
            DB_TYPE: postgresdb
            DB_POSTGRESDB_HOST: postgres
            DB_POSTGRESDB_PORT: 5432
            DB_POSTGRESDB_DATABASE: n8n
            DB_POSTGRESDB_USER: n8n
            DB_POSTGRESDB_PASSWORD: n8n
            N8N_ENCRYPTION_KEY: a_secure_encryption_key_change_this
            NODE_OPTIONS: "--max-old-space-size=4096"
            N8N_HOST: n8n
            N8N_PORT: 5678
            WEBHOOK_URL: "http://localhost:5678"
        volumes:
            - n8n_storage:/home/node/.n8n
        depends_on:
            - postgres
            - ollama

networks:
    app-network:
        driver: bridge

volumes:
    n8n_storage:
    ollama_data:
    postgres_storage:
